openapi: 3.0.3
info:
  title: Allocation API
  description: API for allocation and batch retrieval
  version: 1.0.0
servers:
  - url: http://localhost:8080

tags:
  - name: allocation
    description: Allocation of order lines

paths:
  /allocate:
    post:
      tags:
        - allocation
      summary: Allocate an order
      operationId: allocate
      requestBody:
        description: Order line data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AllocateRequest'
      responses:
        '200':
          description: Successful allocation
          content:
            application/json:
              schema:
                type: string
        '204':
          description: Out of stock
        '400':
          description: Bad request
  /batch/{batch_reference}:
    get:
      tags:
        - allocation
      summary: Get batch information
      operationId: getBatch
      parameters:
        - name: batch_reference
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful batch retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Batch'
        '404':
          description: Batch not found

components:
  schemas:
    AllocateRequest:
      type: object
      properties:
        orderLine:
          $ref: '#/components/schemas/OrderLine'
    OrderLine:
      type: object
      properties:
        orderId:
          type: string
        sku:
          type: string
        quantity:
          type: integer
      required:
        - orderId
        - sku
        - quantity
    Batch:
      type: object
      properties:
        purchasedQuantity:
          type: integer
        allocations:
          type: array
          items:
            $ref: '#/components/schemas/OrderLine'
        reference:
          type: string
        sku:
          type: string
        eta:
          type: string
          format: date-time
      required:
        - purchasedQuantity
        - reference
        - sku
