openapi: 3.0.3
info:
  title: Allocation API
  description: API for allocation and batch retrieval
  version: 1.0.0
servers:
  - url: http://localhost:8080

tags:
  - name: allocation
    description: Allocation of order lines

paths:
  /allocate:
    post:
      tags:
        - allocation
      summary: Allocate an order
      operationId: allocate
      requestBody:
        description: Order line data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AllocateRequest'
      responses:
        '200':
          description: Successful allocation
          content:
            application/json:
              schema:
                type: string
        '204':
          description: Out of stock
        '400':
          description: Bad request
  /batch/{batch_reference}:
    get:
      tags:
        - allocation
      summary: Get batch information
      operationId: getBatch
      parameters:
        - name: batch_reference
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful batch retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Batch'
        '404':
          description: Batch not found
  /batch:
    post:
      tags:
        - allocation
      summary: Create a batch for allocation
      operationId: createBatch
      requestBody:
        description: The new batch to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBatch'
      responses:
        '201':
          description: Batch created successfully
        '400':
          description: Bad request

components:
  schemas:
    AllocateRequest:
      type: object
      properties:
        orderLine:
          $ref: '#/components/schemas/OrderLine'
    OrderLine:
      type: object
      properties:
        orderId:
          type: string
          example: "order123"
        sku:
          type: string
          example: "SKU-123"
        quantity:
          type: integer
          format: int32
          example: 10
      required:
        - orderId
        - sku
        - quantity

    NewBatch:
      type: object
      properties:
        reference:
          type: string
          example: "batch-123"
        sku:
          type: string
          example: "SKU-123"
        purchasedQuantity:
          type: integer
          format: int32
          example: 100
        eta:
          type: string
          format: date-time
          example: "2025-11-15T12:00:00Z"
      required:
        - reference
        - sku
        - purchasedQuantity

    Batch:
      allOf:
        - $ref: '#/components/schemas/NewBatch'
        - type: object
          properties:
            allocations:
              type: array
              items:
                $ref: '#/components/schemas/OrderLine'
