version: 2.1

workflows:
  merge-to-master-verify:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:23.0.1

    steps:
      - checkout

      - run:
          name: "Setup Environment Variables"
          command: |            
            echo 'export GIT_USER_ID="$GIT_USER_ID"' >> "$BASH_ENV"
            echo 'export GIT_PERSONAL_ACCESS="$GIT_PERSONAL_ACCESS"' >> "$BASH_ENV"
            source "$BASH_ENV"

      - run:
          name: Build
          command: mvn -gs settings.xml -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test
