version: 2.1

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

executors:
  my-executor:
    docker:
      - image: cimg/openjdk:21.0

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo 'export USERNAME="$GIT_USER_ID"' >> "$BASH_ENV"
            echo 'export PASSWORD="$GIT_PERSONAL_ACCESS"' >> "$BASH_ENV"
            source "$BASH_ENV"

      - run:
          name: Build
          command: mvn -s settings.xml -B -DskipTests clean package

  test:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo 'export USERNAME="$GIT_USER_ID"' >> "$BASH_ENV"
            echo 'export PASSWORD="$GIT_PERSONAL_ACCESS"' >> "$BASH_ENV"
            source "$BASH_ENV"
      - run:
          name: Test
          command: mvn -s settings.xml test
