version: 2.1

workflows:
  pr-verify:
    triggers:
      - type: pull_requests
        branches:
          only:
            - master
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21

    steps:
      - checkout

      - run:
          name: "Setup Environment Variables"
          command: |
            echo 'export USERNAME="$GIT_USER_ID"' >> "$BASH_ENV"
            echo 'export PASSWORD="$GIT_PERSONAL_ACCESS"' >> "$BASH_ENV"
            source "$BASH_ENV"

      - run:
          name: Build
          command: mvn -s settings.xml -B -DskipTests clean package

      - run:
          name: Test
          command: mvn -s settings.xml test
