DROP TABLE IF EXISTS orderLine;
DROP TABLE IF EXISTS batch;

CREATE TABLE batch
(
    reference          VARCHAR(255) PRIMARY KEY,
    sku                VARCHAR(255),
    purchased_quantity INTEGER,
    eta                TIMESTAMP WITH TIME ZONE
);

CREATE TABLE orderLine
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku             VARCHAR(255),
    quantity        INTEGER,
    order_id        VARCHAR(255),
    batch_reference VARCHAR(255),
    CONSTRAINT fk_batch_reference FOREIGN KEY (batch_reference) REFERENCES batch (reference)
);

-- CREATE TABLE batch
-- (
--     reference         VARCHAR(255) PRIMARY KEY,
--     sku               VARCHAR(255),
--     purchasedQuantity INTEGER,
--     eta               TIMESTAMP WITH TIMEZONE
-- );
--
-- CREATE TABLE orderLine
-- (
--     id              BIGSERIAL PRIMARY KEY,
--     sku             VARCHAR(255),
--     quantity        INTEGER,
--     orderId         VARCHAR(255),
--     batch_reference VARCHAR(255),
--     CONSTRAINT fk_batch_reference FOREIGN KEY (batch_reference) REFERENCES batch (reference)
-- );