name: Cellardoor

on:
  pull_request:
    branches:
      - master

jobs:
  pr-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.16.0
        with:
          java-version: 21
          maven-version: 3.9.9
          settings-servers: |
            [{
              "id": "github",
              "username": "${{ secrets.GIT_USER_ID }}",
              "password": "${{ secrets.GIT_PERSONAL_ACCESS }}"
            }]
          settings-repositories: |
            [{
              "id": "github",
              "name": "cellardoor-bom-repo",
              "url": "https://maven.pkg.github.com/Kronen/cellardoor-bom",
              "snapshots": {
                "enabled": true
              }
            }]

      - name: Run Maven verify
        run: mvn --batch-mode --update-snapshots verify
